dist: trusty
language: node_js
node_js:
  - 8
  - 10
cache: false
#cache:
#  directories:
#    - node_modules
#    - packages/*/node_modules
before_install:
  - npm cache verify
  - npm install -g npm
  - npm --version
script:
  - npm run build
