---
dist: trusty
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
    - packages/dapp/node_modules
    - packages/device-wrapper/node_modules
    - packages/gpcli/node_modules
    - packages/smartcontracts/node_modules
before_install:
  - npm install -g npm lerna
install:
  - lerna bootstrap
script:
  - npm run --prefix packages/smartcontracts build
  - npm run --prefix packages/dapp build
