image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm config -g set script-shell "/msys64/usr/bin/bash"
  - npm install -g npm
  - npm install

before_build:
  - node --version
  - npm --version

build_script:
  - npm run build

test: off
